### ISSUE TITLE
'module' object has no attribute 'to_rgba' when plotting histograms with error bars

### ISSUE THREAD

**Issue by marinang** [scikit-hep/scikit-hep#58] opened 2018-04-23 13:29 UTC
Hi

I was just trying to reproduce the example I here https://github.com/scikit-hep/scikit-hep/blob/master/doc/examples/visual/errorbars.ipynb

```
_ = skh_plt.hist(data, bins=20, errorbars = True)
plt.title('Simple Error Bar Example')
```

 but when errorbars is set to True there is an error 

<img width="1120" alt="capture d ecran 2018-04-23 a 15 29 25" src="https://user-images.githubusercontent.com/24250309/39129577-23a8800e-470b-11e8-9211-6ffb36e5abb9.png">

Matt

**Comment by eduardo-rodrigues** [comment] 2018-04-23 13:35
Cc'ing @brovercleveland as I do not manage to assign this to him ...

**Comment by brovercleveland** [comment] 2018-04-23 13:38
I'll take a look, I have a new update to push with minor bugfixes and optimization.

**Comment by marinang** [comment] 2018-04-23 13:44
This is with python 2.7!

**Comment by marinang** [comment] 2018-05-10 19:34
@brovercleveland  No problem. I'm using matplotlib 2.2.2 .

**Comment by brovercleveland** [comment] 2018-05-15 17:52
Hi @marinang, 
So, I cannot reproduce your error using python 2.7.12 and mpl 2.2.2.  However, I do get another error (which is expected):
`TypeError: _reshape_2D() takes exactly 2 arguments (1 given)`

This is because the current version of scikit-hep is not compatible with mpl >2.1.  My local version has already fixed that minor incompatibility, and I will push it to the master fork after I've cleaned up a few other loose ends.  I'm not sure why you are getting the exact error that you've encountered, however.  It seems to be contingent on the `colors` module from mpl, which should be perfectly valid for the versions you've listed.

Once my fork is pushed, lets check again and see if this error persists?

**Comment by marinang** [comment] 2018-05-15 18:59
Hi @brovercleveland,
It is not impossible that I have updated the matplotlib version in between and of course I don't remember which one I was using :S

**Comment by eduardo-rodrigues** [comment] 2018-07-25 14:21
Can you confirm, @marinang, that PR https://github.com/scikit-hep/scikit-hep/pull/70 fixes your issues, in which case this can be closed. Many thanks.

**Comment by marinang** [comment] 2018-07-25 14:44
Yes, I will have a look.

**Comment by marinang** [comment] 2018-07-26 08:10
@eduardo-rodrigues You can close this issue, I don't encounter this problem  anymore 👍

**Comment by eduardo-rodrigues** [comment] 2018-07-26 08:16
Brilliant, thanks a lot for the confirmation.

**Closed by eduardo-rodrigues** 2018-07-26 08:16 UTC
Labels: bug, skhep.visual

**Comment by atashfeshan** [comment] 2018-09-15 06:54
hi 
I don't know why but this problem just happen with jupyter(or ipython) test your code in  your terminal

**Comment by brovercleveland** [comment] 2018-09-18 14:53
If you're having this issue, please print out what versions of matplotlib, jupyter, and scikit-hep you're using.

**Comment by srugano** [comment] 2018-09-24 10:01
Python : 3.5
jupyter==1.0.0
matplotlib==1.5.1
 I have this error: 

`AttributeError                            Traceback (most recent call last)
/usr/local/lib/python3.5/dist-packages/ipykernel/pylab/backend_inline.py in show(close, block)
     37             display(
     38                 figure_manager.canvas.figure,
---> 39                 metadata=_fetch_figure_metadata(figure_manager.canvas.figure)
     40             )
     41     finally:

/usr/local/lib/python3.5/dist-packages/ipykernel/pylab/backend_inline.py in _fetch_figure_metadata(fig)
    172     """Get some metadata to help with displaying a figure."""
    173     # determine if a background is needed for legibility
--> 174     if _is_transparent(fig.get_facecolor()):
    175         # the background is transparent
    176         ticksLight = _is_light([label.get_color()

/usr/local/lib/python3.5/dist-packages/ipykernel/pylab/backend_inline.py in _is_transparent(color)
    193 def _is_transparent(color):
    194     """Determine transparency from alpha."""
--> 195     rgba = colors.to_rgba(color)
    196     return rgba[3] < .5

AttributeError: module 'matplotlib.colors' has no attribute 'to_rgba'`

**Comment by brovercleveland** [comment] 2018-09-25 19:59
@srugano your version of matplotlib is incompatible with this package, please update to a version greater than 2.0

**Comment by eduardo-rodrigues** [comment] 2018-09-26 08:16
Hi @brovercleveland, maybe a source of trouble is the INSTALL_REQUIRES part which specifies the version of matplotlib only for Py2.7*, seehttps://github.com/scikit-hep/scikit-hep/blob/master/setup.py?

**Comment by ianylow** [comment] 2018-10-03 20:52
Running into the same issue with Pyhton 2.7 and Matplotlib 1.5.3

**Comment by brovercleveland** [comment] 2018-10-03 21:07
Very strange, the relevant line in setup.py is `'matplotlib>2.0.0;python_version>="2.7"`, which i assumed imposed this matplotlib version requirement for all python versions greater than or equal to 2.7 (which is redundant at this point, anyway).  I'm not sure why this condition is not being imposed, I'll have to investigate further.  @ianylow , please update your matplotlib version in the meantime.

**Comment by kambizG** [comment] 2018-12-13 12:15
Same issue here!

<img width="978" alt="screen shot 2018-12-13 at 1 07 57 pm" src="https://user-images.githubusercontent.com/5528894/49937840-56f3a800-fed8-11e8-902f-e214bad0267b.png">

I'm using the following Versions:

<img width="844" alt="screen shot 2018-12-13 at 1 13 45 pm" src="https://user-images.githubusercontent.com/5528894/49938080-0cbef680-fed9-11e8-9cbe-0294151d926b.png">

**Comment by pollackscience** [comment] 2018-12-13 15:32
Please run `pip install -U matplotlib`.  You are using a version of matplotlib that is too old to be compatible with scikit-hep.  You also do not show what version of scikit-hep you are using, but please make sure you are using the latest version (which is compatible with py3.5).

Because this issue keeps occurring, I just tested a fresh install for myself.  I installed python 3.5.6, then installed matplotlib==1.5.1, then installed scikit-hep.  scikit-hep upgrades matplotlib, as expected.  I'm not sure what edge cases allow users to end up with incompatible versions.

**Comment by joemcglinchy** [comment] 2019-04-04 17:54
Also seeing this with the following versions: 

Python:  3.6.7 | packaged by conda-forge | (default, Feb 20 2019, 02:51:38) 
[GCC 7.3.0]
numpy:  1.16.2
matplotlib:  1.5.3

**Comment by pollackscience** [comment] 2019-04-04 18:20
matplotlib 1.5.x is not compatible, please update to a current version

**Comment by pollackscience** [comment] 2019-05-08 17:31
@oppianmatt unfortunately that looks like an edge-case incompatibility that will not be fixed on matplotlib's end, and will likely not be supported here.  I recommend upgrading to python 3 and/or using anaconda to manage python installs on CentOS.
